# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Custom Metadata Panel Guide
description: > # this means to ignore newlines until "baseurl:"
  The Custom Metadata Panel provides Enterprises and individuals with a way to
  focus their attention on critical metadata in one panel.
baseurl: "/custom-metadata" # the subpath of your site, e.g. /blog
github_username:  adobe-dmeservices

# Build settings
markdown: kramdown
remote_theme: "pmarsceill/just-the-docs"
plugins:
  # - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

search_enabled: True
